[tool.black]
line_length = 88

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true

[tool.flake8]
max-line-length = 88
max-complexity = 10
ignore = ["E203", "E266", "E501", "W503", "W504"]
per-file-ignores = ["*/__init__.py: F401"]
exclude = ".git, __pycache__, build, dist"
